- name: nginx install and run the server
 hosts: web
 become: yes # for root access in adhoc cmd..-b, bydefault : no
 tasks: 
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: start the nginx server
    ansible.builtin.service:
      name: nginx
      state: started  


